num= int(input("Enter the required number:"))
print(f"{num}*1={num}")
print(f"{num}*2={num*2}")
print(f"{num}*3={num*3}")
print(f"{num}*4={num*4}")
print(f"{num}*5={num*5}")
print(f"{num}*6={num*6}")
print(f"{num}*7={num*7}")
print(f"{num}*8={num*8}")
print(f"{num}*9={num*9}")
print(f"{num}*10={num*10}")

num1 = int(input("Enter num1:"))
num2 = int(input("Enter num2:"))

print(f"The power of these 2 numbers is {num1} and {num2}:",pow(num1,num2))
